### PR TITLE
Added logging entries for all states

### PR DESCRIPTION
**Pull request by jjkd**
Before issuing a pull request, please see the contributing page.

Corrected typo in state name

### CODE REVIEW

**Comment by jjkd** [comment]
See additional logging and correction of extra character in state name,

**Comment by jjkd** [comment]
Note that since you have added a class for states and so forth, you may need to do extra work to get OpModeIsActive available to all of the class run methods, as you must test this if any of these methods end up containing any type of loop.  Hopefully the state methods can be designed to be inline code only, no loops.  That way, the only loop will be at the main state machine level.

**Comment by downquark7** [comment]
Note that this will generate hundreds of mostly useless logs every second because the .run() is intended to be run every loop.

**Comment by jjkd** [comment]
Hundreds, yes, mostly useless, yes, however not entirely useless.  What is
useful is that from this data you can determine exactly how long it takes
to perform certain operations, how long it takes for the robot to
transition from one state to another, how long it will coast while changing
power levels or directions, how frequently the sensors can be polled, how
often the line can be checked for, determine the degree of error expected
in the line detection, determine the degree of error expected in the
heading from the gyro and so forth. Once you have that data, and make the
necessary alterations to compensate for those values, the logging can then
be commented out.

## 

Joe Kyle
--jjkd--

**Comment by jjkd** [comment]
In 
-        everyTime();
-        if (conditionsToCheck()) {
-            this.onCompletion();
-            currentState++;
-            robotconfig.addlog(dl, "StateMachine", "Execution of " + this.name + " has been completed");
-        }

the call to everyTime() should be after the if.   When the conditions for the transition out of the state are true, you don't want to call everyTime() at all.  So, test comes first, then the execution of the state.

```
    if (conditionsToCheck()) {
        this.onCompletion();
        currentState++;
        robotconfig.addlog(dl, "StateMachine", "Execution of " + this.name + " has been completed");
    } else {
      everyTime();
    }
```

**Comment by downquark7** [comment]
How do I make a .CSV log?

**Pull request merged**
